spring:
  application:
    name: parent-ms
server:
  port: 8084
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  renewalPercentThreshold: 0.85
  server:
    enableSelfPreservation: false